### ISSUE TITLE
Feature Request: Give the option to hide the "Show sidebar suggestions" button

### ISSUE THREAD

**Issue by Pharaz4** [lawrencehook/remove-youtube-suggestions#104]
I Would Just like the option to hide the button that says "show sidebar suggestions".

**Comment by lawrencehook** [comment]
There's already this option, called "Add a button to reveal suggestions" and you can disable it. But you bring up a good point. I'm planning to add an 'x' to the button to make it easier to disable.

![image](https://github.com/lawrencehook/remove-youtube-suggestions/assets/6572030/e40117ef-b9cb-44b3-bbaf-5c8ee70e0115)

**Comment by lawrencehook** [comment]
Added an 'x' to the reveal buttons.

<img width="292" alt="image" src="https://github.com/lawrencehook/remove-youtube-suggestions/assets/6572030/618339bd-ec7c-436a-bb1f-f4f8080cfdd5">
