### ISSUE TITLE
Hide Channels in the left sidebar

### ISSUE THREAD

**Issue by koolx** [lawrencehook/remove-youtube-suggestions#11]
Remove Youtube Suggestions can't hide the sidebar from subscriptions and channel. How do I fix this?

**Comment by emumoo** [comment]
I don't quite know what you mean, can you attach a screenshot?

**Comment by dbogdanov** [comment]
Perhaps, he means the left sidebar. I agree it will be useful to hide "Subscriptions" from that sidebar because they contain notifications if any new video is out. Also, it's just nice to hide the channels one follows. If that is it, I was going to file a similar issue.

**Comment by lawrencehook** [comment]
👍  an option to hide "subscriptions" sounds like a good idea to me

**Comment by lawrencehook** [comment]
![image](https://user-images.githubusercontent.com/6572030/192789796-9e706ced-973c-4ef7-ba36-ce03440eda93.png)

Done!

**Comment by geedogz** [comment]
3 years later? Are u serious???

**Comment by lawrencehook** [comment]
Always happy to merge pull requests :)
