### ISSUE TITLE
Invidious/Piped compatibility

### ISSUE THREAD

**Issue by darkwater4213** [lawrencehook/remove-youtube-suggestions#110]
Invidious and Piped are popular privacy-respecting frontends to Y*uTube. A large reason I switched to Invidious is its inherently more-hackable nature. I'd appreciate this also applying to those two sites (well... they're both self-hosted so that might be a little bit of an issue: https://instances.invidious.io/)

**Comment by Jon-guy30** [comment]
Honestly it shouldn't bee too difficult to add. Look at SponsorBlock, it runs on both front-ends through a setting, just accept the additional permissions (I think it was some 60 websites it asked for permission :P) and it works. 

To be fair these sites already have ways to reduce distractions such as removing the recommended feed from the settings.

**Comment by darkwater4213** [comment]
Necroposting aside...

Invidious already has a setting to remove suggestions. What I actually want is certain content to be suggested: unwatched videos for channels I have already subscribed to. Anything else is most probably a waste of my time.

This should probably be an Invidious and/or Piped FR or even just a straight-up fork. Closing. :)
