### ISSUE TITLE
Feature request: Remove "For You"-shelf on youtube channel home-pages.

### ISSUE THREAD

**Issue by Kerst1** [lawrencehook/remove-youtube-suggestions#112]
I would like to be able to hide this section shown in the screenshot below:
![foryou](https://github.com/lawrencehook/remove-youtube-suggestions/assets/56637456/04977a4a-87f4-4518-8210-62528ad95651)

Thanks

**Comment by hapybratt** [comment]
Yes, please do this. I came to this page specifically to see if its been suggested!

**Comment by lawrencehook** [comment]
thanks for the feedback! I'll aim to push a new version today or tomorrow

**Comment by lawrencehook** [comment]
The latest version (4.3.52) has just been released, and includes an option to "Hide the For You section"

Thanks again for the feedback
