### ISSUE TITLE
Feature Request: Adding a functionality for self destructing the YouTube tab on completion of a specified video by the user

### ISSUE THREAD

**Issue by yaten2302** [lawrencehook/remove-youtube-suggestions#115]
# About
Hi @lawrencehook,
This is a feature request for adding a functionality that will self destruct the YouTube tab when a particular video is completed.
The idea of this feature is as follows:
![image](https://github.com/lawrencehook/remove-youtube-suggestions/assets/129659514/f3ba78ef-404e-4759-b0be-19e83af45775)
A new setting can be added in this section and inside it, a toggle option can be there. If the user turns this feature on, then a url will be asked to enter a url and on completion of that video, the tab will self destruct.
<br>
## How this feature will be beneficial
This will help users tackle procrastination as the tabs will destruct on their own.

**Comment by lawrencehook** [comment]
Hello, it's a good idea but I'm not sure if it's possible to implement. I'll investigate

**Comment by yaten2302** [comment]
Hi @lawrencehook,
If this feature is required, then may I also work on it?

**Comment by lawrencehook** [comment]
Certainly! Feel free
