### ISSUE TITLE
True full screen mode

### ISSUE THREAD

**Issue by Jon-guy30** [lawrencehook/remove-youtube-suggestions#117]
Remember in the old youtube days when you full-screened a video it would stay full screen? Now when you do that, if you scroll down you can actually read the comments that way. In keeping with the spirit of this extension it would be cool if we could remove that behavior.  

There was an extension that has this feature but I forget its name.

What do you think?

What I mean: 
![Skärmbild (7)_LI](https://github.com/lawrencehook/remove-youtube-suggestions/assets/10241225/89c70e72-5734-4332-9950-80df7bd7a2d8)

**Comment by lawrencehook** [comment]
Good idea! I'll add this the next time I work on RYS

**Comment by porobertdev** [comment]
> Good idea! I'll add this the next time I work on RYS

Hey, I've seen that you added the label.

How are you gonna approach this? I looked into it for like an hour, and what I came up with was to just toggle  `display: none` on the bottom container, so that there's nothing to scroll on.

**Comment by lawrencehook** [comment]
Hi yea I'll probably do something like that. There's a problem I ran into where that approach seems to break the layout when the video is no longer full screen. But there should be a simple way of detecting if its in full screen mode or not.

**Comment by porobertdev** [comment]
> Hi yea I'll probably do something like that. There's a problem I ran into where that approach seems to break the layout when the video is no longer full screen. But there should be a simple way of detecting if its in full screen mode or not.

What about an event listener that selects `.ytp-fullerscreen-edu-button` which is the "arrow down" showing up on fullscreen and check if it has "display: none" that YT sets?

**Comment by lawrencehook** [comment]
Thanks, sounds promising. I'll check it out.

I tried mutation observers a while ago but it'd cause some lag on slower machines. I might not have configured it well though.

**Comment by lawrencehook** [comment]
3d6c476bfe33db8066d544b2912f663e1b8810c6

**Comment by lawrencehook** [comment]
implemented! as of version `4.3.53`. firefox is updated -- and chrome will take a couple days
