### ISSUE TITLE
Feature Req: Clean up "You >" section.

### ISSUE THREAD

**Issue by JasonJAyalaP** [lawrencehook/remove-youtube-suggestions#118]
The "You >" line in the sidebar deserves to be hidden, a long with "Your channel" and "Your Videos" for most people. Perhaps "Liked Videos" too.  An option to auto-expand "show more" for playlists would be useful for anyone with less than a million playlists. The <hr> or horizontal bars above and below that section are bloated whitespace. While I'm here: Sorting playlists alphabetically would blow my mind. 

Thanks for your work, Lawrence!

**Comment by lawrencehook** [comment]
Good ideas! Thanks, I'll add the next time I work on this

**Comment by lawrencehook** [comment]
61b9a321231523bc4f8263715bfa203ec9a7c62f

done! should be updated on Firefox, chrome will take a day or so
