### ISSUE TITLE
Feature Request - Add an option to automatically revert back to Blocking/hiding after x amount of time of turning it off

### ISSUE THREAD

**Issue by bhavyaw** [lawrencehook/remove-youtube-suggestions#121]
Thanks for amazing extension. 

Just a request for small feature - I block all homepage suggestions but very seldom I turn it off when I slack a little bit. But I don't want it to be remained turned off for longer periods of time. I want the blocking to automatically turn on after the user decided time, say 3 hrs or 1 day. 

If you think this can be a good feature, I can think of some ideas of how to go about it and eventually raise a PR for the same. Let me know. Thanks!

**Comment by lawrencehook** [comment]
Hi thanks for making an issue, something like this already exists.

![image](https://github.com/lawrencehook/remove-youtube-suggestions/assets/6572030/10295dd3-3f7b-4c5d-81eb-8f306563f3bb)

It turns of the extension for up to 3 hours. There's also a "schedule" feature where you can decide when the extension should be active. Supports things like "workdays from 9 to 5" and is pretty flexible.

![image](https://github.com/lawrencehook/remove-youtube-suggestions/assets/6572030/cd394df6-913f-4301-bbb0-8e113d7d9094)
