### ISSUE TITLE
Feature Request: Unlock volume slider

### ISSUE THREAD

**Issue by AlexVeeBee** [lawrencehook/remove-youtube-suggestions#132]
Youtube limits the volume to 50% or higher instead of 100% and its starting to annoy me and i want to listen to music on full blast or any other video

On the top is the Picure-in-Picture turned on and on the bottom is youtube

| Image | Video |
|-|-|
| ![opera_oZsGOnpQQ3](https://github.com/lawrencehook/remove-youtube-suggestions/assets/75509525/774e54c0-aeba-46d4-9a5f-aa14c87d0d68) | https://www.youtube.com/watch?v=skRN9ZZ1XyU |
| ![opera_IotlpARqGu](https://github.com/lawrencehook/remove-youtube-suggestions/assets/75509525/90f0860c-b233-418c-8df1-915667e72ffd) | https://www.youtube.com/watch?v=qIpuvZG0Xd4&t=252s |

Browser: OperaGX

**Comment by lawrencehook** [comment]
I'm not seeing that 50% limit, perhaps it's an Opera bug?

**Comment by AlexVeeBee** [comment]
it does seem to happen to me, even in incognito mode

**Comment by AlexVeeBee** [comment]
This does not seem to be going anywhere
