### ISSUE TITLE
Configure a time schedule for removing suggestions

### ISSUE THREAD

**Issue by dbogdanov** [lawrencehook/remove-youtube-suggestions#14]
It will be useful to have an option to specify time intervals when one wants to activate the distraction-free mode (similar to LeechBlock) by day (e.g., only block on Mon-Fri) and hour.

**Comment by emumoo** [comment]
I like this idea! I haven't had much free time lately, but I think this feature should be the next thing to be implemented.

**Comment by Jackalaq** [comment]
Great idea!  Just downloaded for the first time, alongside LeechBlock.  If adding time controls, then perhaps add the capacity to temporarily disable (e.g. 'Allow for next 10 minutes' button).  This button would be great if presented with feedback with number and total duration of additional videos played or times button has been pressed...  A way to count the cost of distraction!
Thanks so much for the Add-on.

**Comment by lawrencehook** [comment]
Finally got around to implementing this :)

The latest version (4.3.27) has a scheduling feature as well as options to turn on/off for limited period.

Thanks for the comments!
