### ISSUE TITLE
Disable annotations not working

### ISSUE THREAD

**Issue by clicky6** [lawrencehook/remove-youtube-suggestions#140]
Disable annotations is turned on but it is not doing that & annotations are still showing like the watermark at the bottom right, Turning annotations off from settings button on youtube video disables it.
Demonstration video below:-

https://github.com/user-attachments/assets/b6b8e229-0e8d-454e-9e25-292f08c28835

**Comment by lawrencehook** [comment]
016194e31dc9a56a996e3a17151650f90e5d8fcf

Release pending! though I don't even see that annotations toggle anymore...

**Comment by lawrencehook** [comment]
released as of version `4.3.62`
