### ISSUE TITLE
Change thumbnails size

### ISSUE THREAD

**Issue by Niji-Bemani** [lawrencehook/remove-youtube-suggestions#142]
We can hide or blur the thumbnails, but it would be also great to be able to reduce the thumbnails size : 

## Current
![image](https://github.com/user-attachments/assets/83176c17-ef7a-4dd8-8b2d-382d7b6255a4)

## Wanted
![image](https://github.com/user-attachments/assets/1c63a782-d1c1-4098-aec8-668a08712d51)

For now, I managed to script that : https://greasyfork.org/en/scripts/508444-small-youtube-thumbnails

**Comment by lawrencehook** [comment]
e9b2af8f873d17c99113f618e2363bdca687c49e

Release pending!

**Comment by lawrencehook** [comment]
released as of version `4.3.62`
