### ISSUE TITLE
Get bigger video view when sidebar ist disabled

### ISSUE THREAD

**Issue by georgkrause** [lawrencehook/remove-youtube-suggestions#145]
I have no right sidebar in my youtube view, however the video doesn't take the full because there is still an empty HTML-element:

```html
<div id="panels-full-bleed-container" class="style-scope ytd-watch-flexy"></div>
```

As soon as I remove this, the video gets bigger. It would be nice if this could be done automatically.

**Comment by lawrencehook** [comment]
Even when this option is enabled?

<img width="344" alt="image" src="https://github.com/user-attachments/assets/4bc9bf17-9a61-456b-ad27-788922497f72" />

**Comment by georgkrause** [comment]
@lawrencehook I had this option enabled, however I am unable to reproduce this today. I am confused. I will close this until I run into the issue again.

Sorry for the noise and thank you for the kind reply and the great plugin!
