### ISSUE TITLE
Firefox android plugin: suggestions not removed

### ISSUE THREAD

**Issue by lkorczowski** [lawrencehook/remove-youtube-suggestions#16]
Hi,

Many thanks for this great plugin!

I'm using firefox android 68.0 to watch youtube (https://m.youtube.com) and the homepage shows a list of suggestions that aren't removed with this plugin.
Note that if I use "request desktop site", the suggestions are removed correctly.

Any hint for making it work on the mobile version of youtube?

Thanks

Plugins installed:
- Remove Youtube Suggestions 3.0.4
- Disable Facebook News Feed 1.6
- RescueTime for Firefox 3.2.3
- uBlock Origin 1.21.2
- Video Background Play Fix 1.5
- OpenH264

**Comment by lawrencehook** [comment]
@lkorczowski I don't have an Android phone so it'll be hard for me to test, but this is a good idea. I'll give it a shot!

**Comment by lawrencehook** [comment]
Just released a version (4.2.23) that should work on mobile. Fingers crossed!
