### ISSUE TITLE
Collision with some adblockers by redirection on YT

### ISSUE THREAD

**Issue by rmnwnsx** [lawrencehook/remove-youtube-suggestions#19]
I think, there are an issue with [AdBlocker Ultimate](https://addons.mozilla.org/en-US/firefox/addon/adblocker-ultimate/?src=search), because the Add-One don't properly work by redirection on YT from other pages:
![grafik](https://user-images.githubusercontent.com/47259322/71723731-10982080-2e2e-11ea-8d9b-99156be8d7c2.png)

But when I go to the video from YT Search and open video in the same tab it works :
![grafik](https://user-images.githubusercontent.com/47259322/71723711-f9f1c980-2e2d-11ea-8328-8c9bdb35c260.png)

However it also don't work when i open the video in the new tab. Same for [Ghostery](https://addons.mozilla.org/en-US/firefox/addon/ghostery/?src=search). But e.g. [uBlock Origin](https://addons.mozilla.org/en-US/firefox/addon/ghostery/?src=search) works properly. 

I use Firefox 68.3.0esr (64-Bit) on Debian 10

**Comment by lawrencehook** [comment]
Hi @rmnwnsx  Is this still an issue?
