### ISSUE TITLE
Block "More Videos" when video pauses on non youtube domains

### ISSUE THREAD

**Issue by SNaushadS** [lawrencehook/remove-youtube-suggestions#24]
I observed that the More Videos block does show up when a YouTube Video is embedded in a non YouTube webpage.

It will be great if this can be blocked as well.

![Screenshot 2020-09-24 at 11 36 32 AM](https://user-images.githubusercontent.com/1532907/94106991-34871080-fe5a-11ea-86ca-00a75664ea6d.png)

**Comment by remi-garcia** [comment]
I like that this add-on is kept in `["*://*.youtube.com/*"]`. I don't think removing the "More videos" block is possible keeping this restriction.

**Comment by emumoo** [comment]
Good note SNaushadS, but I agree with remi-garcia

**Comment by SNaushadS** [comment]
i understand what @remi-garcia says. I feel that the extension will serve the purpose even better when this restriction is moved out, Or probably provided as a setting to user. Do let me know your thoughts @emumoo

**Comment by remi-garcia** [comment]
I am still a novice in this domain (add-on development) but if I understood well, this kind of restriction cannot be user defined but is an overall parameter of the add-on. If I'm right, then I think it would be necessary to have two independent add-ons.

However, it might be possible to provide a workaround: for users that have TamperMonkey or similar it should be possible to propose a script that does what @SNaushadS is suggesting. IMHO it would be a good compromise as the "More videos" box can be closed, thus preventing it to show is not as useful as the rest of this add-on.

**Comment by lawrencehook** [comment]
I believe this is fixed as of de72e29c65aefead79cb22a48dd0a1f6b5bcc920

Didn't require more permissions! Simply enabling `all_frames` did the trick
