### ISSUE TITLE
[Feature Request] Add extension to the quick access menu

### ISSUE THREAD

**Issue by yannxaver** [lawrencehook/remove-youtube-suggestions#25]
It would be awesome if the extension was in the quick access menu and could be toggled on and off with a single click. There are some moments when I want to turn it off.

**Comment by lawrencehook** [comment]
Hi @yannxaver, I'm not sure what the quick access menu is. Can you attach a screenshot?

**Comment by lawrencehook** [comment]
I believe this has been resolved. The icon has been moved to where most extension icons are.
