### ISSUE TITLE
Playlists no longer visible with new version

### ISSUE THREAD

**Issue by ragnarookie** [lawrencehook/remove-youtube-suggestions#26]
My Firefox (84.0.2) updated the plugin to version 3.3.0 today and in opposite to the old version, playlists are no longer visible.  For tutorials they're often like a "select chapter" option and pretty useful.

For example:
https://www.youtube.com/watch?v=lnFN6YabFKg&list=PLZ-54sd-DMAKU8Neo5KsVmq8KtoDkfi4s

Can you make them visible again or add a toggle to chose whether they become invisible?

**Comment by lawrencehook** [comment]
That's no good! thanks for bringing it to my attention, I'll push a fix ASAP

**Comment by lawrencehook** [comment]
Should be fixed as of version 3.3.1

**Comment by ragnarookie** [comment]
Thank you!
