### ISSUE TITLE
Link to Trending page no longer working

### ISSUE THREAD

**Issue by D3SOX** [lawrencehook/remove-youtube-suggestions#27]
YouTube changed it to <kbd>Explore</kbd>

![image](https://user-images.githubusercontent.com/24937357/111378905-c9005c00-86a2-11eb-86d8-956018ae5078.png)

**Comment by lawrencehook** [comment]
Good catch, thanks D3SOX!

I pushed an update just now. The Firefox version is updated, and Chrome is pending...
