### ISSUE TITLE
Add option to redirect homepage to library

### ISSUE THREAD

**Issue by lawrencehook** [lawrencehook/remove-youtube-suggestions#45]

**Comment by mylastresort** [comment]
hello please could you guys consider having some extra options for the redirect homepage feature, I would like to have the option to redirect youtube feed homepage to library only when I'm reaching youtube app in the address bar. and thank you.

**Comment by lawrencehook** [comment]
![image](https://user-images.githubusercontent.com/6572030/192789338-c415270f-ecbf-43b2-bf59-3ab6edf3c026.png)

@mylastresort It's there! Added a couple days ago
