### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by tjallemaal** [lawrencehook/remove-youtube-suggestions#46]
Hey, I just installed the extension, but then I saw it is listed among firefox's addons anyway. 
I just wanna know, just in case I might want to uninstall it.

Thanks for this great extension!

Appreciate it.

**Comment by tjallemaal** [comment]
on my command line it says:
`added 591 packages, and audited 592 packages in 52s`
 how do I remove them?

**Comment by lawrencehook** [comment]
Not sure I'm following exactly. The `added 591 packages, and audited 592 packages in 52s` message is from npm, the node package manager. It downloads packages into a node_modules folder. I believe removing them is a simple matter of deleting the folder.

Removing the extension from firefox is another matter. Should be fairly straightforward from the `about:addons` page.

**Comment by tjallemaal** [comment]
I've looked into `about:addons`, it's not there.
But I ran it already in the command line, namely via`web-ext run`.

Sorry bothering, I'm just not so tech savvy

**Comment by lawrencehook** [comment]
All good.

If you just want to install the extension to Firefox, go [here](https://addons.mozilla.org/en-US/firefox/addon/remove-youtube-s-suggestions/) and click "Add to Firefox".

The `web-ext run` command is for getting started with dev work.

**Comment by tjallemaal** [comment]
> All good.
> 
> If you just want to install the extension to Firefox, go [here](https://addons.mozilla.org/en-US/firefox/addon/remove-youtube-s-suggestions/) and click "Add to Firefox".

Yes! But i've already installed it the "dev" way, so I want to first uninstall it...

> The `web-ext run` command is for getting started with dev work.

Yeah, when I saw  that it's available in the firefox "store" it was too late

**Comment by tjallemaal** [comment]
Is there a CLI command to uninstall it ? I don't want to pollute my harddrive

**Comment by lawrencehook** [comment]
> i've already installed it the "dev" way

The "dev" way is temporary. As soon as the `web-ext run` process stops (for example with `ctrl+c`), there won't be an installation anywhere.

**Comment by tjallemaal** [comment]
alright! thanks lawrence. I'm just too ignorant
