### ISSUE TITLE
Extension not working in mobile version of YouTube

### ISSUE THREAD

**Issue by MathevsBatista** [lawrencehook/remove-youtube-suggestions#47]
Hello, I use YouTube through the kiwi browser, which is a chrome-based mobile browser that works with the chrome extensions, your extension works normally on YouTube when I click to show the computer version, but when I'm viewing the version mobile, it doesn't work and YouTube becomes addictive again. Please, make it compatible with mobile version.

To test: install kiwi browser in your cellphone, install the extension through chrome extensions and open youtube.

**Comment by lawrencehook** [comment]
Just released a version (4.2.23) that should work on mobile. Fingers crossed!
