### ISSUE TITLE
Gratitude and feature request.

### ISSUE THREAD

**Issue by skrazee** [lawrencehook/remove-youtube-suggestions#48]
Thank you for such a wonderful add on for Firefox. I would like to request you to add option for **hiding** **"Best of YouTube**", **"More from YouTube"** option. Many of us do not sign in to youtube for privacy reason. It would have been great if there would have a **local subscription option**.

**Comment by mateuszjablonski** [comment]
What do you mean by "local subscription option"? You can use any RSS reader to subscribe to any channel. I am using https://netnewswire.com/ and it is working great.

**Comment by skrazee** [comment]
I mean like [New Pipe](https://github.com/TeamNewPipe/NewPipe) app. There is a option for saving a channel (Subscribe to channels) as local subscription.

**Comment by mateuszjablonski** [comment]
I think this is entirely out of scope of this plugin. You can look for any RSS plugin for your browser and use it instead.

**Comment by skrazee** [comment]
I agree.
