### ISSUE TITLE
Add option to hide "menu buttons" - thumbs, saving, sharing, etc.

### ISSUE THREAD

**Issue by mateuszjablonski** [lawrencehook/remove-youtube-suggestions#50]
This uBlock entry hides the items:

```
! 2022-03-15 https://www.youtube.com
www.youtube.com###menu-container
```

Before:
<img width="400" alt="before" src="https://user-images.githubusercontent.com/7666514/158408267-3e9cc165-1000-4766-8d41-5326c65e05a8.png">

After:
<img width="400" alt="after" src="https://user-images.githubusercontent.com/7666514/158408306-9df3a4e5-3156-4d87-87fa-244fe62f7944.png">

**Comment by lawrencehook** [comment]
Good idea, thanks for posting!

I'll add a new setting to remove these menu items

**Comment by lawrencehook** [comment]
Added!

860449ab70a3618f935c3edf83976ff2bd37363c
