### ISSUE TITLE
Does not work anymore

### ISSUE THREAD

**Issue by BoostCookie** [lawrencehook/remove-youtube-suggestions#51]
With the current YouTube UI it does not work anymore.
I have tested version 4.2.10 on Firefox 98.0.1 and on Chromium 99.0.4844.74, both on Linux 64 bit.

**Comment by remi-garcia** [comment]
Same versions (Add-on and Firefox) and OS (Ubuntu 64bit), it works fine. Do you use other add-ons?

**Comment by BoostCookie** [comment]
On Firefox I've used a private window and have this Add-on set as the only Add-on that is allowed in private windows.
For Chromium I've used a brand new installation.
The attached screenshots are with Chromium.
![extensioninsettings](https://user-images.githubusercontent.com/62076789/159126441-4037f1fe-a702-4cb8-8806-0b934c5a0b8b.png)
![youtubewithsuggestions](https://user-images.githubusercontent.com/62076789/159126442-77202c80-7238-43b6-85c7-62a98d90f0ea.png)

**Comment by lawrencehook** [comment]
I changed the default on/off setting to "off" recently. That might explain it?

I've since changed the default back to "on", but it will take a few days for the the update to go live on Chrome.

**Comment by BoostCookie** [comment]
> I changed the default on/off setting to "off" recently. That might explain it?

Ok, that was it. Seems to be a weird default behaviour to me, good that you've changed it back. I honestly don't get why that is even an option since you can also deactivate extensions in Firefox and Chromium.

But ok, this works for me now. Thanks.
