### ISSUE TITLE
"Redirect the Homepage" option redirects music.youtube.com

### ISSUE THREAD

**Issue by spfanning** [lawrencehook/remove-youtube-suggestions#53]
Setting Redirect the homepage to subscriptions in firefox redirects https://music.youtube.com/ to the the youtube subscriptions page. This seems like unintended behavior.

**Comment by lawrencehook** [comment]
Indeed, good catch! Thanks for pointing it out. I'll upload a fix shortly

**Comment by lawrencehook** [comment]
@spfanning Fixed as of 1bb7c06d3209104478115e0e86a3dac43346d891

Firefox is updated, and Chrome usually takes a day or so.

Thanks again!

**Comment by spfanning** [comment]
Thanks!
