### ISSUE TITLE
Add support for m.youtube.com when using Firefox extension on Android

### ISSUE THREAD

**Issue by shbach** [lawrencehook/remove-youtube-suggestions#55]
Similar to #47 but specifically requesting support for Android version of Firefox.

It is possible to use any Firefox extension on Android [by using collections in the nightly version](https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/). Currently though, when I enable it on my phone, it doesn't work with the mobile version of youtube.

**Comment by lawrencehook** [comment]
Thanks for creating the issue. Agreed, having this extension work on mobile would be nice. Pasting a reddit comment to help future me dev for the mobile version of the site.

> You can use [this link](http://m.youtube.com/?persist_app=1&app=m) to force the mobile site, and [this link](http://www.youtube.com/?persist_app=1&app=desktop) to reset to the desktop site.

**Comment by JJRcop** [comment]
If you don't want to use Firefox Nightly because of stability, you can also use [Fennec F-Droid](https://f-droid.org/en/packages/org.mozilla.fennec_fdroid/), a build of Firefox for F-Droid with a few patches that enable some options like the collections feature in Nightly.

**Comment by lawrencehook** [comment]
5dd4f81180893b961760afc974b98873be87c6df

Just released a version that should be mobile compatible.

I tested with the mobile site, on my laptop. I don't have an Android so I can't test it there, but hope it works!

**Comment by JJRcop** [comment]
That's a perfectly fine way to test because I can verify with my phone it works perfectly. Thanks so much!

**Comment by shbach** [comment]
@lawrencehook I can also verify that it now works on mobile! Thanks so much! As of now, among all the YouTube blocking extensions, this is the only one that actually works on the mobile website.
