### ISSUE TITLE
Hide all shorts

### ISSUE THREAD

**Issue by borderline232** [lawrencehook/remove-youtube-suggestions#57]
If you could implement a feature in which youtube shorts videos are redirected to the normal youtube player that would be awesome. 

The workflow for it is pretty simple:

Shorts video URL = `youtube.com/shorts/<video-id>`

Normal video URL = `youtube.com/watch?v=<video-id>`

You just need to mutate the shorts video URL to the normal one and it should work out. Thanks again.

**Comment by remi-garcia** [comment]
Hiding shorts would also be a nice feature

**Comment by lawrencehook** [comment]
![image](https://user-images.githubusercontent.com/6572030/174439507-d5023678-3040-4c57-b570-ac456a3d424e.png)

@borderline232 Already implemented! There's an option called `Redirect shorts` in the "video player" section.

**Comment by lawrencehook** [comment]
@remi-garcia Good idea. I'll add it to my list. There's an existing option for hiding shorts from search results, so hiding them everywhere should be a straightforward addition.

**Comment by 0xatulpatil** [comment]
Hey Lawrence, can I take up this issue? 
As most of the part is already implemented, this would be an easy first issue for me.

**Comment by lawrencehook** [comment]
@0xatulpatil Certainly!

**Comment by 0xatulpatil** [comment]
Great! How do you want me to go about it? 

All the short badges are marked using appropriate attributes on the "Results" and "Subscription" page. Would need to mark them on the homepage as well. Using CSS selectors we can hide them all at once. 

Will this be a good starting point? Any other suggestions?

**Comment by lawrencehook** [comment]
That's a great starting point. I believe there's also shorts on the sidebar.

Sounds like you have a good understanding of how the code works.

There's a question of which section to put the new option under, but that can wait.

**Comment by 0xatulpatil** [comment]
I think this feature does not belong to any specific section that currently exists in our options menu, so "Basic" would be the best place to put it IMO.

Also, what should I name it? "Hide all shorts" or "Hide Shorts everywhere"?

**Comment by lawrencehook** [comment]
Good idea and "Hide Shorts everywhere" sounds good to me

**Comment by 0xatulpatil** [comment]
#73 
@lawrencehook  made a PR for the same, let me know if there are any changes to me made

**Comment by lawrencehook** [comment]
@0xatulpatil Awesome, I'll do some testing and get back to you. Will probably take a couple days.

**Comment by lawrencehook** [comment]
@0xatulpatil Merged, thanks!

I added some updates to handle shorts that appeared in the sidebar.

0c6cec355a84d9dcd6ed60d16e6898fb0922cc0b
