### ISSUE TITLE
Left sidebar extra hide subscriptions

### ISSUE THREAD

**Issue by mhimranhossain** [lawrencehook/remove-youtube-suggestions#60]
# I used ublock to hide this section of the YouTube

![Left Side bar hide subbed channels](https://user-images.githubusercontent.com/50992812/189796808-24dc5408-29ab-494b-bdbf-0ca45b80035f.jpg)

### this used to work before the update few months ago but now left sidebar extra doesn't hide subbed channels for me!

**Comment by lawrencehook** [comment]
![image](https://user-images.githubusercontent.com/6572030/192789504-f11858f0-83a9-47a5-8541-1557605cf7ea.png)

@mhimranhossain Done! Added a couple days ago. Thanks for making this issue.
