### ISSUE TITLE
Loved the feature "Hide Search bar suggestions" any way to get that done on google.com?

### ISSUE THREAD

**Issue by IshanChhangani** [lawrencehook/remove-youtube-suggestions#61]
Great extension any possibility to extend that to google.com as well?

**Comment by lawrencehook** [comment]
Thanks. Extending to another site is outside of the scope of this extension. Perhaps there's another one that does it?

**Comment by IshanChhangani** [comment]
Is there another extension for Google that does this? I have been searching for the same but I can't find. Can you suggest if you know.
Thank you.

**Comment by lawrencehook** [comment]
Here's an article that looks promising, but I haven't tested it

https://www.makeuseof.com/tag/how-to-disable-search-suggestions-on-every-major-browser/
