### ISSUE TITLE
"Hide the entire left sidebar" Breaks with playlists

### ISSUE THREAD

**Issue by IshanChhangani** [lawrencehook/remove-youtube-suggestions#62]
![image](https://user-images.githubusercontent.com/91928381/193568403-9789074f-d4e9-4eb0-83d4-f50076e2af71.png)
![image](https://user-images.githubusercontent.com/91928381/193568808-077e64d4-29e2-456f-99c0-cea9350c05ab.png)

**Comment by lawrencehook** [comment]
That's certainly broken. Good catch! I'll fix it in the next few days

**Comment by lawrencehook** [comment]
<img width="1171" alt="image" src="https://user-images.githubusercontent.com/6572030/194783249-136fb326-dcdd-4814-bb0d-6fdf5fbf0020.png">

@IshanChhangani Just released a fix (version 4.3.8). Thanks again

**Comment by harkamalsr** [comment]
Just wanted to say that with the newer versions of the extension this issue is back once again. It might be related to Youtube's UI update

![image](https://user-images.githubusercontent.com/10123690/214890665-c1dbb4b3-61fd-4351-b053-d18ddbddb372.png)

**Comment by lawrencehook** [comment]
@harkamalsr good catch! it's broken for me too. I'll try to push a fix in the next day or so

**Comment by lawrencehook** [comment]
fixed!
