### ISSUE TITLE
Homepage settings apply to channel video page in redesign

### ISSUE THREAD

**Issue by JJRcop** [lawrencehook/remove-youtube-suggestions#63]
With the youtube redesign, the videos tab of youtube channels are affected by the homepage settings of RYS. It seems that with the redesign, the videos tab now functions similarly to the homepage.

I have some example screenshots

### Homepage settings enabled
![Screenshot_20221029_142022](https://user-images.githubusercontent.com/5211576/198828534-bcfaeba0-8e63-4b87-b1bc-665521413cef.png)

### Homepage settings disabled
*hide extra rows doesn't change anything, since there are no extra rows in the videos tab*
![Screenshot_20221029_142323](https://user-images.githubusercontent.com/5211576/198828671-cbd308c2-2c6a-4692-ab23-e5b232d4ecb6.png)

**Comment by lawrencehook** [comment]
Good catch. Thank you for creating this issue @JJRcop 

Should be a simple fix, I'll add a check to flag whether or not the current page is the homepage.

**Comment by lawrencehook** [comment]
@JJRcop Should be fixed as of version 4.3.13

17d53da252853f3757181202925f2816b5307a35

Thanks again for making the issue.

**Comment by JJRcop** [comment]
17d53da252853f3757181202925f2816b5307a35 fixes it, thanks!

**Comment by lawrencehook** [comment]
going to keep this open until the fix is approved by Chrome

**Comment by lawrencehook** [comment]
deployed!
