### ISSUE TITLE
disable playlist autoplay

### ISSUE THREAD

**Issue by Jon-guy30** [lawrencehook/remove-youtube-suggestions#65]
So I've been using this extension for a while now, one thing that is missing in my opinion is to disable the autoplay in youtube playlists. 
In the video player UX section there's a Disable autoplay feature, but that's for general videos, not the playlists. If you could implement such a feature that'd be awesome!

Why do I want such a feature?

In the new youtube "redesign", they removed the feature to sort videos by old in the youtube channel videos tab. Now if I want to list all videos I have to go to a channel's Home tab click on uploads playlist, click play all and then yet again click on the uploads playlist that appears. Then I can scroll down. The issue with playlists is that it's impossible to disable autoplay, I have to take out the "&list=" in the URL and the YouTube playlist ID or whatever it is to not be in the playlist view in order to disable autoplay. There is another way to list all videos a channel has too, go to the channels search bar and type asterisk (*) i.e. the wildcard argument and it will list all the videos a channel has uploaded, but they're all over the place and not in any order.

So again, if you could figure out how to do that would be awesome!

**Comment by lawrencehook** [comment]
Hi @Jon-guy30 

Thanks for making an issue!

There's now an option "Disable autoplay for playlists" as of version 4.3.15.

8383bfa313bfa830297af95fb95e241172c2c8a4

**Comment by lawrencehook** [comment]
Released on Firefox

Chrome will take a while

**Comment by lawrencehook** [comment]
reopening until it's released on Chrome

**Comment by Jon-guy30** [comment]
Now that is fast, thanks!

**Comment by lawrencehook** [comment]
deployed!
