### ISSUE TITLE
Shorts in Search Result

### ISSUE THREAD

**Issue by 0xatulpatil** [lawrencehook/remove-youtube-suggestions#67]
For some reason, I am seeing shorts on my results page even though I have have disabled shorts in search results.

![image](https://user-images.githubusercontent.com/67235572/208229545-8d9f5248-2cb3-41eb-8ae5-d39112c8eada.png)

**Comment by lawrencehook** [comment]
Good catch! Thanks for making the issue.

That row of shorts must be a recent change by YouTube.

I'll try to push a fix in the next few days.

**Comment by 0xatulpatil** [comment]
Hey Lawrence, would love to help you with this. Though I'm pretty new to extensions, with your little help I think I can fix this.
Let me know If I can help.

**Comment by lawrencehook** [comment]
@0xatulpatil Awesome :) no pressure though

The fix will likely be 1 new line in the main.css file, around here

**Comment by 0xatulpatil** [comment]
Thanks for the nudge, will try to fix this issue once I am free.

Thanks once again.

**Comment by lawrencehook** [comment]
6bf713ded628fb6bf58c515318426a57ab90ab75

**Comment by lawrencehook** [comment]
Implemented!

Should be live on Firefox, and Chrome will take a day or two
