### ISSUE TITLE
Create a userscript version

### ISSUE THREAD

**Issue by KeyuanHuang** [lawrencehook/remove-youtube-suggestions#68]
Hello! I'm wondering whether this extension could be made into a userscript because I want to use it on my iPad. Usually iOS browsers don't support extensions well, but it could run userscripts. If you could do this, I would appreciate it a lot!

**Comment by KeyuanHuang** [comment]
> Hi! Thanks for posting. I haven't used userscripts on iOS before. Seems out of scope for this project, but I agree that something like RYS on iOS/mobile would be good!

Userscript is Safari's counterpart of Chrome's tampermonkey, an extension that can add some javascript code to some website. I tried to copy your `main.css` and `content-script.js` into an ugly userscript like [this](https://github.com/KeyuanHuang/remove-youtube-suggestions/blob/Crude-userscript-version/RYS.user.js), where I delete the code for dynamic settings. It seemed to work and hide the YouTube suggestions, but the shorts were not removed; maybe I did something wrong. So I think it's possible for RYS to work as a userscript on iOS.

Maybe the settings could be made like [Tweak New Twitter](https://github.com/insin/tweak-new-twitter/blob/master/tweak-new-twitter.user.js), a chrome extension that also has a userscript version. Users can change the settings using the `config` json at the beginning of the code. But I'm not very familiar with javascript so I can't organize the code well and make all the functions work. If you could make a userscript version of RYS, it would be perfect.

**Comment by KeyuanHuang** [comment]
> Hi! Thanks for posting. I haven't used userscripts on iOS before. Seems out of scope for this project, but I agree that something like RYS on iOS/mobile would be good!

By some slight modifications of your `main.css` and `content-script.js`, I've got a userscript that satisfies my needs well. Thank you for your awesome code!

**Comment by lawrencehook** [comment]
That's great, you're welcome!

Feel free to publish it if there's a repository/marketplace of userscripts somewhere

**Comment by KervynH** [comment]
Here's a userscript version. https://github.com/KervynH/Focused-YouTube
