### ISSUE TITLE
Disable Ambient mode and Annotations

### ISSUE THREAD

**Issue by BoostCookie** [lawrencehook/remove-youtube-suggestions#69]
By default Ambient mode and Annotations are enabled. I have to disable them manually each session. Would be nice if this extension could take care of that.

**Comment by lawrencehook** [comment]
Good idea, I'll add it to my list

**Comment by lawrencehook** [comment]
Implemented!

48581ae1a39b4a3f26f2cb0b74c3b54237f7dff1

**Comment by BoostCookie** [comment]
It only works after clicking on the Settings of a video. Is it possible to make it work immediately?

**Comment by lawrencehook** [comment]
@BoostCookie thanks for letting me know.

The latest version (4.3.27) should have a fix.

**Comment by BoostCookie** [comment]
I'm sorry, but I'm on 4.3.33 now and it now does not work at all anymore. Annotations and Ambient Mode just stay on now, even after clicking the settings wheel.

**Comment by lawrencehook** [comment]
hmm... do you mind sending me a screenshot of the menu after clicking the settings wheel?

**Comment by BoostCookie** [comment]
![screenshot](https://user-images.githubusercontent.com/62076789/224343339-8c169503-2c41-4460-994f-3c85e31a4c79.png)
There you go.

**Comment by lawrencehook** [comment]
Danke! What other YouTube extensions do you have installed?

**Comment by BoostCookie** [comment]
Bitte! I also have [Return YouTube Dislike](http://returnyoutubedislike.com/) and [SponsorBlock](https://sponsor.ajay.app/). Though for testing I've now set your AddOn to be allowed in private windows (and it is the only one allowed in private windows). So there should not be any clashes with other AddOns in a private window. And the problem still appears.
Are you not able to reproduce it? I'm on Firefox 110.0.1 (64-bit).

**Comment by lawrencehook** [comment]
Yea it's working okay for me, I'm on the same version of Firefox too. The next time I work on this I'll try switching to the German site and see if I can reproduce it.

**Comment by BoostCookie** [comment]
My YouTube is set to
Language: English (US)
Location: Germany
I have no idea about Firefox extensions, but could the OS make a difference? I'm on Artix Linux.

**Comment by lawrencehook** [comment]
Just pushed a potential fix: version (4.3.34)
