### ISSUE TITLE
Disable video play on hovering

### ISSUE THREAD

**Issue by remi-garcia** [lawrencehook/remove-youtube-suggestions#70]
On homepage, videos automatically widen and start on mouse hovering.

Could disabling that behavior be added to the add-on?

**Comment by lawrencehook** [comment]
Thanks for making an issue. 

I've tried to implement this in the past with no luck, but I'll give it another go.

**Comment by remi-garcia** [comment]
If needed I'll try to find time to resolve this issue, thank you for the nice work anyway :)

This might help:
https://greasyfork.org/en/scripts/391615-disable-previews-on-youtube-firefox/code
https://gist.github.com/matter-it-does/bc3acea114ef3962973de54fba57509a (this option requires to modify cookies, which does not seem to be a great idea for this add-on)

**Comment by lawrencehook** [comment]
Thanks for the pointers!

I implemented it using the cookie approach.

48581ae1a39b4a3f26f2cb0b74c3b54237f7dff1

Not sure if it will work everywhere, but it works for me

**Comment by remi-garcia** [comment]
Great, works for me. Thanks!

I though that it would require more permissions to modify a cookie 🤔 

Nice job 👍🏼
