### ISSUE TITLE
Add ability to export/import settings

### ISSUE THREAD

**Issue by shbach** [lawrencehook/remove-youtube-suggestions#71]
There is a lot of configurable options available in this extension and when I install this extension on another computer/browser, it's a bit of work to replicate my preferred settings. It would be great if there was some sort of settings export/import option to make that easier to do.

**Comment by lawrencehook** [comment]
Good idea! I'll add it to my list

**Comment by lawrencehook** [comment]
Just released a new version (4.3.18) with import/export.

Thanks again for the feedback
