### ISSUE TITLE
UI issue in YT

### ISSUE THREAD

**Issue by Pontiac76** [lawrencehook/remove-youtube-suggestions#77]
Since probably the last couple of days, I noticed that when in full screen mode while watching YT, the title of the video flashes in the upper right corner of the video.

I also noticed that when I'm in the subscription list, that if I click on the three dots to save a video to a play list, or what have you, the popup immediately disappears.  You see it, then it closes.  It's ALMOST like when you've got an auto-clicker gone mad.

I don't know if it's a conflict, but if I turn off this add on while still watching YT, the flickering title stops, and back in the playlists, I can click successfully on the three dots.

I'd say this is something new, as I don't recall this happening yesterday morning.  Might have been in the late evening (Eastern time, currently -4 GMT)

**Comment by lawrencehook** [comment]
Thanks for making the issue.

Something wonky is happening on my end too. Will try to release a fix asap

**Comment by lawrencehook** [comment]
The latest version (4.3.29) should be fixed

Here's the relevant commit 7a07bbabf8932eb72f2414c0cfad78bc898175e1

Let me know if something's still up though. Thanks again!

**Comment by lawrencehook** [comment]
another fix incoming...

**Comment by Pontiac76** [comment]
Confirmed that I can get the popup when I click on the dots, but the flashing of the title still is occurring when in full screen mode.  If that's the "next fix" cool.

**Comment by lawrencehook** [comment]
@Pontiac76 I can't recreate the title flashing bug. Do you mind sending me your settings? There's an option to export in the settings menu (the three dots top-right in RYS options).

**Comment by Pontiac76** [comment]
[rts.txt](https://github.com/lawrencehook/remove-youtube-suggestions/files/10893240/rts.txt)

**Comment by lawrencehook** [comment]
thank you! Okay, I think it's all fixed now as of version 4.3.30

**Comment by Pontiac76** [comment]
Thank you.  Looks good at quick glance.  (Doing coding myself so trying to not distract myself. ;) )

**Comment by Pontiac76** [comment]
Seems like the flickering is back this morning in full screen mode?  It WAS looking fine last night.

If I use your UI option to turn RYTS off temporarily, the flashing stops.

This seems to ONLY be when in full screen.  This is after a recent reboot of the machine as well (Other oddities were going on outside FF)

**Comment by Pontiac76** [comment]
Also, to note, if I hover over the video in full screen when the HTML5 shows the progress bar and play buttons at the bottom and such, the flashing stops.  But if you stop the mouse long enough so that the additional bars go away, the flashing continues.

**Comment by lawrencehook** [comment]
Hmm.... just to be sure can you check what version you're on? You can find it at the bottom of the feedback page.

**Comment by lawrencehook** [comment]
Just released another update (4.3.32). I haven't been able recreate the bug, but it might be fixed

**Comment by Pontiac76** [comment]
I ran the update check before I posted just to make sure.  FF said things were good, nothing updated.  But going back in, checking, it started to flash.  Just to be certain, I kicked up a couple of other videos and it continued to do the flicker.  I toggled the plugin on and off to check my sanity, and yeah, the flickering stopped when the plugin was off, then immediately started again when on.  So I posted here, and went on with what I'm doing while having FF in the background

But, then I started actually just finished watching a video now, and it wasn't flickering.  Confused, I again kicked up a couple of more videos, making sure that the plugin was on, and no more flickering.

I don't know what to say about this.

I just pulled the update now (After this text above) and I see the comment about fixing the text flicker.

Version
4.3.33

The one thing I did notice as well (Feature!) is that if I immediately move off the video in full screen mode, the bar and title go away.  Me-Likey.

**Comment by lawrencehook** [comment]
Glad to hear it's working again, hopefully for good this time :) Thanks for the help

I used some hard-coded queries that perhaps would only work sporadically. I think that should be fixed now, but we'll see!

I'll close the issue if there's no more trouble for a couple days.
