### ISSUE TITLE
Suggestion: Auto-focus on the search input

### ISSUE THREAD

**Issue by Brog33** [lawrencehook/remove-youtube-suggestions#79]
It would be awesome to have an option to toggle auto-focus on the search input field on the front page - so you're ready to type & search instantly.

**Comment by lawrencehook** [comment]
Good idea, I'll add it to my list

**Comment by lawrencehook** [comment]
As of the latest version (4.3.36) there's an option to autofocus the search bar.

![image](https://user-images.githubusercontent.com/6572030/227077598-7e37e022-74fb-4ae5-9138-142349e93965.png)

**Comment by Brog33** [comment]
This works great! 
However auto focus does open the autocomplete suggestion-list when there is text already present in the search field. I would propose to only set focus when the search field is empty.
