### ISSUE TITLE
Another extension ("Dark Mode") prevents removal of sidebar suggestions

### ISSUE THREAD

**Issue by whatareyoutalkingaboutyousoundinsane** [lawrencehook/remove-youtube-suggestions#8]
When both this extension and the popular [Dark Mode](https://mybrowseraddon.com/dark-mode.html) extension are enabled—and it doesn't matter if Dark Mode's switch is toggled to light or dark mode—YouTube sidebar suggestions remain visible. Homepage suggestions are removed fine though.

**Comment by emumoo** [comment]
Thanks for letting me know about Dark Mode, seems neat! I'll check it out, should be a straightforward fix.

**Comment by doncentrons** [comment]
Hi, I have the same issue with a similar extension: Dark Reader [https://darkreader.org/](url)
thank you for the great extension!

**Comment by BloodRaven0** [comment]
Well, youtube does have a pretty good dark mode in itself, so disabling these addons for youtube only seems to be a good enough fix.
