### ISSUE TITLE
Flickering bug on settings/right-click menus in video player

### ISSUE THREAD

**Issue by stenovera** [lawrencehook/remove-youtube-suggestions#81]
Hello, today I encountered an issue with the settings button bringing up the menu for a millisecond then disappearing - it is impossible to select options from it. Occasionally it flickers a few times this way, but will still disappear. Same issue with right-clicking the video player - the menu appears for a millisecond and disappears. Disabling the app fixes this. Did not have this issue yesterday. I'm running the Brave Browser, which uses the Chrome version of the extension (4.3.28) - if a later update fixes it, I don't know how to install it.

**Comment by lawrencehook** [comment]
Update: the fix is up on Chrome
