### ISSUE TITLE
Search Bar in Channel Videos Tab Disappears.

### ISSUE THREAD

**Issue by slysnake96** [lawrencehook/remove-youtube-suggestions#82]
I love this extension.
However there is a bug now that causes the search bar in a channels video section to constantly disappear when you try to click on it.
This makes it impossible to actually search a channels video section for a specific video.
As soon as I disabled the extension the search bar went back to being usable again.
The attached image shows the search bar working when the extension is disabled.
When the extension is enabled the search bar show in the picture will pop up for half a second then disappear again instantly making it impossible to actually search for anything.
![Inked2023-03-07 21_30_30-](https://user-images.githubusercontent.com/56527115/223397192-b5a637a2-4c13-4be5-8e4a-edb1d3d1bba3.jpg)

**Comment by lawrencehook** [comment]
Hi thanks for making an issue!

I believe this bug should be fixed as of the latest version (4.3.33) which is released on Firefox and should be up on Chrome in the coming day or so. There were a bunch of related bugs, see #77.

**Comment by slysnake96** [comment]
Thanks heaps, glad to see you are so supportive of the community and quick to issue fixes for any bugs :D
