### ISSUE TITLE
Homepage redirect has recently become unreliable

### ISSUE THREAD

**Issue by ketsuban** [lawrencehook/remove-youtube-suggestions#83]
I've had RYS set to redirect the useless homepage to my subscriptions for a long time now, and recently I've noticed it's become unreliable—more often than not it doesn't work at all, and when it does work rather than being near-seamless there's now a perceivable period where it starts loading the homepage and then switches to the subscriptions.

I'm using Firefox 110.0.1 on Windows 11. In addition to RYS I have SponsorBlock and uBlock Origin installed along with a few other addons which shouldn't have any effect on Youtube (the only other one that could is Stylus, and I have no styles that affect Youtube).

**Comment by lawrencehook** [comment]
Thanks for making the issue. I'll look into it. Something's wonky on my end too, the homepage simply reloads over and over. And when I reload the subscriptions page, YouTube will automatically redirect to the homepage. Doesn't happen for the Watch Later or Library pages.

**Comment by lawrencehook** [comment]
@ketsuban I attempted to make the redirect more reliable in the latest version (4.3.36). Let me know if it's still wonky.

**Comment by ketsuban** [comment]
The redirect seems to be more reliable now, but it really wants to *keep* me on the subscriptions page when I try to navigate away by clicking on one of the channels I follow or doing a search.

**Comment by lawrencehook** [comment]
Oh good catch. Just released a fix (4.3.37). It's live on Firefox, will take a day or so for Chrome.

**Comment by lawrencehook** [comment]
@ketsuban Is it better now?

**Comment by ketsuban** [comment]
Yes, sorry, it's working perfectly now.
