### ISSUE TITLE
Playlists now sometimes have "Recommended videos" tagged on at the end.

### ISSUE THREAD

**Issue by bluelightzero** [lawrencehook/remove-youtube-suggestions#85]
No idea what the criteria for youtube deciding to do it, as it only appears on one of my playlists.

![image](https://user-images.githubusercontent.com/4492982/225587002-1fbee336-d0b6-4724-8d27-24ceae6aa0cc.png)

There is no point sharing a link, because it does not show up for other profiles. You have to be logged in on my account for it to show up on this specific playlist, so good luck finding a playlist that activates it.

**Comment by lawrencehook** [comment]
Thanks for making the issue. There's a new option to disable playlist suggestions as of the latest version (4.3.36)

![image](https://user-images.githubusercontent.com/6572030/227077337-928caa41-10e7-4726-80fb-73bd0bb8b3c3.png)
