### ISSUE TITLE
Prevent the search prediction list from showing when autofocusing on the search bar

### ISSUE THREAD

**Issue by Brog33** [lawrencehook/remove-youtube-suggestions#86]
In reference to https://github.com/lawrencehook/remove-youtube-suggestions/issues/79

Regarding "autofocus the search bar":
If the search bar already contains text when focus is set, a list of predictions pop up and covers parts of the screen. It would be beneficial to either prevent the prediction-list from triggering on focus, or perhaps to only set focus when the search bar is empty.

**Comment by lawrencehook** [comment]
@Brog33 Thanks for making the issue! Sorry I've been meaning to reply to your comment on #79.

Should be a simple fix, I'll work on it in the next few days.

**Comment by lawrencehook** [comment]
deployed!
