### ISSUE TITLE
[Feature Request] Add an option to blur the video thumbnails just like unhook

### ISSUE THREAD

**Issue by CodeCubeNeo** [lawrencehook/remove-youtube-suggestions#92]

**Comment by CodeCubeNeo** [comment]
Sorry not unhook, but his add-on: https://github.com/domdomegg/hideytthumbnails-extension

**Comment by lawrencehook** [comment]
Good idea! I'll look into adding this feature.

**Comment by lawrencehook** [comment]
![image](https://github.com/lawrencehook/remove-youtube-suggestions/assets/6572030/ffb5d0df-ee87-4d92-b971-c3cfa043d487)

![image](https://github.com/lawrencehook/remove-youtube-suggestions/assets/6572030/06272db6-efeb-4018-aac2-ef8a79c29b1e)


Added as of version 4.3.45. Thanks again for the feedback.
