### ISSUE TITLE
[Feature Request] Add an option to hide video's description.

### ISSUE THREAD

**Issue by HoVeRzzz** [lawrencehook/remove-youtube-suggestions#94]
First of all, thank you for all the hard work. Loving the project, and the fact that it is open source!
I wanted to ask the addition of the "hide video's description" feature, I think it would be a good feature to implement to this already great extension.
Thank you, keep up.

**Comment by lawrencehook** [comment]
Good idea, thanks for making an issue. I'll add an option to hide the description.

**Comment by lawrencehook** [comment]
![image](https://github.com/lawrencehook/remove-youtube-suggestions/assets/6572030/463a1193-c7b4-4f54-a508-1d75648715f9)

Added, as of version 4.3.45. Thanks again for the feedback.
