### ISSUE TITLE
Remove shorts from youtube subscritpion page

### ISSUE THREAD

**Issue by graph-knight** [lawrencehook/remove-youtube-suggestions#96]

**Comment by lawrencehook** [comment]
fixed as of 4.3.42!

**Comment by graph-knight** [comment]
can you also make the blank item which before is a youtube short video on the row replace with the videos that in the page so it can look normal page without shorts

**Comment by 0xatulpatil** [comment]
Hey, the feature to "hide shorts" have stopped working for me too. I think there were some changes made by Youtube.

**Comment by 0xatulpatil** [comment]
Hey the feature works, but now the layout is messed up. The shorts are being removed, but they still occupy the dom space.

![image](https://github.com/lawrencehook/remove-youtube-suggestions/assets/67235572/0dcd7fe4-d154-42e5-b595-16e553d93c16)

**Comment by graph-knight** [comment]
yeah that's what I told him, I tried to fix it with my little knowledge about coding if i find something i will send it here

**Comment by graph-knight** [comment]
I think This code will fix the problem I guess:

ytd-section-list-renderer[page-subtype='subscriptions'] ytd-item-section-renderer:has(ytd-expanded-shelf-contents-renderer #thumbnail[href^='/shorts/' i]), /** Shorts in subscriptions list view **/
ytd-guide-renderer ytd-guide-section-renderer:nth-child(1) ytd-guide-entry-renderer:has(#endpoint[title='Shorts'], #endpoint[title='ショート']), /** Icon in sidebar **/
ytd-mini-guide-renderer ytd-mini-guide-entry-renderer > a:not([href]), /** Icon in collapsed sidebar **/
ytm-browse ytm-single-column-browse-results-renderer .scbrr-tabs .scbrr-tab[href$='/shorts' i], /** Tab in channel **/
ytd-rich-grid-renderer[is-shorts-grid], /** Tab in channel inner grid **/
ytd-search ytd-item-section-renderer ytd-shelf-renderer, /** Seach results 'popular today' **/
ytd-reel-shelf-renderer, /** history **/
ytd-browse[page-subtype='subscriptions'] ytd-grid-video-renderer:has(#thumbnail[href^='/shorts/' i]), /** Subsciption feed grid view **/
ytd-watch-next-secondary-results-renderer ytd-item-section-renderer ytd-compact-video-renderer:has(#thumbnail[href^='/shorts/' i]), /** shorts in recommended videos right beside playing video **/
ytd-search ytd-video-renderer:has(#thumbnail[href^='/shorts/' i]), /** search results **/
ytd-rich-section-renderer:has(.ytd-rich-section-renderer[is-shorts]), ytd-rich-section-renderer:has(ytd-rich-shelf-renderer[is-shorts]) /** home **/
{
  display: none !important;
}

**Comment by wedcf120** [comment]
**after hide shorts video should rearrange videos on the grid**



https://github.com/lawrencehook/remove-youtube-suggestions/assets/21985575/1585a5c3-4896-4e80-9c9a-9a7660eb1c80
